### PR TITLE
[WIP] Redesign the Nikola website

### PR DESCRIPTION
**Pull request by Kwpolska**
This is #20, and is a work in progress.  Comments, improvements and ideas welcome.  cc @Aeyoun, @ralsina.

## Front page

* A true landing page.
* Six features described.
* Written in HTML (for flexibility).
* We could color the icons distinctively, but that needs someone more intelligent when it comes to design.

image

## Getting started guide

Done, see below.

### CODE REVIEW

**Comment by Aeyoun** [comment]
* You can colorize the icons with CSS or SVG filters. More flexible and easily changed than bitmaps. Maybe pop them out in nikola-logo-yellow when hovering the section they represent?
* Use [(CSS) hyphenation](http://caniuse.com/#feat=css-hyphens) with the justified text blocks.

**Comment by Aeyoun** [comment]
How about removing the logo in the menu on the front page, and going for a hero instead? It’s just a SVG so it will be no slower to load than the smaller menu-logo (use that—current styling— for every sub-page).

front-page-hero-logo

**Comment by Kwpolska** [comment]
* `.index-icon-static { color: blue }` is enough (those are fonts, not SVGs).
* Mind patching hyphenation in yourself?
* While it looks nice, I would prefer to keep a bit of consistency with the navbar. How about adding a big logo in the jumbotron?

**Comment by Kwpolska** [comment]
## Getting Started Guide

* A step-by-step guide, with prose on the left and command output on the right.
* Parts are duplicated with the manual; we need something to deduplicate it (partials?) or drop that part from the manual.
* We need something to keep the commands from getting split between lines, any suggestions? (last paragraph)

image

**Comment by Kwpolska** [comment]
# Features page

With a right-side ToC, has affix but not scrollspy (not compatible with those lists)

TODO:
- [ ] more features (any ideas?)
- [ ] page for `fast`, eg. a speed comparison (I could get working on 
- [ ] page for `auto`, with a demo video (@ralsina?)

image

# Next steps

- [ ] more things from the checklist (#20) should be done
- [ ] any more things need changing?
- [ ] deploy
- [ ] optional: blog post so people can check it/our new propaganda out

**Pull request merged**
